# Setup
title:            Marquinhus Gonçalves
tagline:          'Blog sobre desenvolvimento Front-End'
description:      'Desenvolvedor Front-End'
baseurl:          ""
url:              https://marquinhusgoncalves.com
author:           'Marquinhus Gonçalves'
email:            eu@marquinhusgoncalves.com
github:           https://github.com/marquinhusgoncalves
twitter:          https://twitter.com/marquinhusgonc
disqus_username:  marquinhusgoncalves

# google_analytics:
account:          UA-103801239-1

# Build settings
markdown:       kramdown
highlighter:    rouge
permalink:      /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# exclude my node related stuff
exclude: [
  'Gemfile',
  'Gemfile.lock',
  'node_modules',
  'vendor/bundle/',
  'vendor/cache/',
  'vendor/gems/',
  'vendor/ruby/'
  'package.json',
  'src',
  'gulpfile.js',
  'testlinks.sh',
  '.travis.yml',
  ]

# Config date
months:
    - Janeiro
    - Fevereiro
    - Março
    - Abril
    - Maio
    - Junho
    - Julho
    - Agosto
    - Setembro
    - Outubro
    - Novembro
    - Dezembro