# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Marquinhus Goncalves
tagline:          'blog sobre desenvolvimento'
description:      'Desenvolvedor front end '
url:              http://marquinhusgoncalves.com.br
baseurl:          /

author:
  name:           'Marquinhus Goncalves'

# Custom vars
version:          1.0
paginate: 5

github:           https://github.com/marquinhusgoncalves
twitter:          https://twitter.com/marquinhusgonc

# google_analytics:
account:          UA-XXXXX-X

# disqus:
id:               disqusid

