# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Marquinhus Goncalves
tagline:          'blog sobre desenvolvimento'
description:      'Desenvolvedor front end '
url:              http://marquinhusgoncalves.com.br
baseurl:          /

author:
  name:           'Marquinhus Goncalves'
  url:            https://twitter.com/marquinhusgonc

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/marquinhusgoncalves
