# Setup
title:            Marquinhus Gonçalves
tagline:          'Blog sobre desenvolvimento Front-End'
description:      'Desenvolvedor Front-End'
url:              http://marquinhusgoncalves.com
baseurl:
author:           'Marquinhus Gonçalves'

# Build settings
markdown:       kramdown
highlighter:    rouge
permalink:        /:title

# Custom vars
version:          1.0
paginate: 		    5

email:            eu@marquinhusgoncalves.com
github:           https://github.com/marquinhusgoncalves
twitter:          https://twitter.com/marquinhusgonc
disqus_username:  marquinhusgoncalves

# google_analytics:
account:          UA-XXXXX-X

