# Setup
title:            Marquinhus Gonçalves
email:            eu@marquinhusgoncalves.com
tagline:          'Blog sobre desenvolvimento Front-End'
description:      'Blog sobre desenvolvimento Front-End - HTML, CSS e Javascript'
baseurl:          /
url:              http://marquinhusgoncalves.com
author:           'Marquinhus Gonçalves'

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:title

# Custom vars
version:          1.0
paginate: 		    5

github:           https://github.com/marquinhusgoncalves
twitter:          https://twitter.com/marquinhusgonc
disqus_username:  marquinhusgoncalves

# google_analytics:
account:          UA-XXXXX-X