# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:             [jekyll-paginate, jekyll-gist]

# Setup
title:            Marquinhus Goncalves
tagline:          'Blog sobre desenvolvimento Front-End'
description:      'Desenvolvedor Front-End'
url:              http://marquinhusgoncalves.com.br
baseurl:          /
author:           'Marquinhus Goncalves'

# Custom vars
version:          1.0
paginate: 		    5

email:            marquinhusgoncalves@hotmail.com
github:           https://github.com/marquinhusgoncalves
twitter:          https://twitter.com/marquinhusgonc
disqus_username:  marquinhusgoncalves

# google_analytics:
account:          UA-XXXXX-X
